export const DATA = [
  {
    id: 1,
    url: "jagu.webp",
    position: [-9.9, 0, -7],
    rotation: [0, Math.PI / 2, 0],
    title: "La Roche Jagu",
    description: "This project, carried out in partnership with the Domaine Départemental de la Roche Jagu, aimed to completely rethink the park visitor experience...",
    tools: "Made with Illustrator, Affinity & Figma",
    credits: "Milo Navellou, Annaëlle Le Guénic, Nuno Enes, Karina Kervadec, Antonin Thomas",
    year: "2025",
    client: "Domaine de la Roche Jagu",
    link: "https://milonavellou.framer.website/work/roche-jagu",
  },
  {
    id: 2,
    url: "musee.webp",
    position: [-9.9, 0, 2],
    rotation: [0, Math.PI / 2, 0],
    title: "Musée Aman in Morocco",
    description: "Under the direction of Mr. El Mandour, I had the opportunity to oversee the entire creation of the website...",
    tools: "Made with Figma & Wordpress",
    credits: "Milo Navellou",
    year: "2025",
    client: "Mohammed VI Museum & Ministry of Habous and Islamic Affairs",
    landscape: true,
    link: "https://milonavellou.framer.website/work/musee-aman",
  },
  {
    id: 3,
    url: "celtic.webp",
    position: [-9.9, 0, 11],
    rotation: [0, Math.PI / 2, 0],
    title: "Celtic'GO",
    description: "The aim of this project was to address a local issue: the fragmentation of cultural offerings...",
    tools: "Made with Figma & Photoshop",
    credits: "Milo Navellou & Elijah Guillou",
    year: "2025",
    client: "IUT Lannion",
    link: "https://milonavellou.framer.website/work/celticgo",
  },
  {
    id: 4,
    url: "mascherata.webp",
    position: [9.9, 0, 2],
    rotation: [0, -Math.PI / 2, 0],
    title: "Mascherata",
    description: "Inspired by Venetian craftsmanship, the Mascherata project involves designing a complete e-commerce ecosystem for a luxury costume brand...",
    tools: "Made with Figma & Prestashop",
    credits: "Milo Navellou & Annaëlle Le Guénic",
    year: "2026",
    client: "Personal Project",
    landscape: true,
    link: "https://milonavellou.framer.website/work/mascherata",
  },
  {
    id: 5,
    url: "spider.webp",
    position: [9.9, 0, -7],
    rotation: [0, -Math.PI / 2, 0],
    title: "Spider Man Calendar",
    description: "This project offers an ethical advent calendar (“Bright Patterns”) inspired by Spider-Man...",
    tools: "Made with Figma, React & Fl Studio",
    credits: "Milo Navellou, Nathan Perissat, Elijah Guillou, Noémie Bouvier, Diane Le Garrec, Harena Ramasindraïbe & Thibault Sardou",
    year: "2025",
    client: "Camille Boulestin & Thomas Bouchez",
    link: "https://www.figma.com/proto/mKFQLTRfjHHJLWvgcpTLsZ/Workshop-Spider-verse?node-id=0-1&t=3ob7DtqfItZN6YBh-1",
  },
];